# Overnight measurement run.
#
# Three A/B tests at enough game counts to actually resolve small differences,
# then a data-generation run with whatever time is left. Everything writes to
# overnight.log as it goes, so a partial run is still useful.
#
# Nothing here is destructive: no existing net, dataset or weight set is
# overwritten, and the engine default is unchanged until a result justifies it.

$ErrorActionPreference = "Continue"
$log = "overnight.log"

function Announce($text) {
    $line = "[{0}] {1}" -f (Get-Date -Format "HH:mm:ss"), $text
    Write-Output $line
    Add-Content -Path $log -Value $line
}

Announce "=== overnight run starting ==="

# 1. Does null-move pruning help? Implemented but never once measured; the build
#    plan flagged it as risky in a variant this volatile. 600 games gives roughly
#    +-28 Elo, enough to tell a real gain from a real loss.
Announce "--- 1/4 null-move pruning, 600 games ---"
$r = .\target\release\gauntlet.exe --pairs 300 --movetime 1000 --a hand --b hand --null-a --seed 8112 2>$null |
     Select-String "vs hand"
Announce "NULLMOVE $r"

# 2. Do the piece-square tables and the three added terms pay? This is the main
#    event: 2000 games is roughly +-15 Elo, which will resolve the +47 the
#    30-game smoke test hinted at.
Announce "--- 2/4 v2 (piece-square tables) vs current tuned, 2000 games ---"
$r = .\target\release\gauntlet.exe --pairs 1000 --movetime 1000 --a v2 --b hand --seed 90210 2>$null |
     Select-String "vs hand"
Announce "V2-vs-TUNED $r"

# 3. Cumulative gain over the spec's starting guesses, for the record.
Announce "--- 3/4 v2 vs spec weights, 600 games ---"
$r = .\target\release\gauntlet.exe --pairs 300 --movetime 1000 --a v2 --b spec --seed 4242 2>$null |
     Select-String "vs hand-spec"
Announce "V2-vs-SPEC $r"

# 4. Fresh data for the next tuning pass, generated by the current default
#    engine. Deliberately not v2: the default is the known-good one until test 2
#    says otherwise, and better-labelled data helps whichever wins. Partial
#    output is usable -- the trainer drops a truncated final record.
Announce "--- 4/4 generating fresh data with the current default engine ---"
.\target\release\selfplay.exe --games 20000 --depth 6 --out data\gen2.bin --seed 20260803 2>&1 |
    Select-String "positions|throughput|games  " | ForEach-Object { Announce "SELFPLAY $_" }

Announce "=== overnight run complete ==="
